### ISSUE TITLE
It will make redis outof memory

### ISSUE THREAD

**Issue by yswtrue** [kodless/leek#46] opened 2021-10-31 11:16 UTC
It will make redis out of memory when running for about 2 days.
![image](https://user-images.githubusercontent.com/1270490/139580327-b9b4339d-3529-4946-ba4d-6bb0f675c30f.png)

**Comment by Stubatiger** [comment] 2021-11-04 16:49
I would guess this is less something about leek and more about your celery setup id assume?

Can you give more info about your environment and settings?

**Comment by yswtrue** [comment] 2021-11-06 09:59
```
version: "2.3"
services:
  agent:
    image: kodhive/leek
    environment:
      # General
      - LEEK_API_LOG_LEVEL=INFO
      - LEEK_AGENT_LOG_LEVEL=INFO
      # Components
      - LEEK_ENABLE_API=false
      - LEEK_ENABLE_AGENT=true
      - LEEK_ENABLE_WEB=false
      # URLs
      - LEEK_API_URL=https://xxx
      - LEEK_WEB_URL=https://xxx
      - LEEK_ES_URL=https://xxx:443
      # Authentication
      - LEEK_API_ENABLE_AUTH=false
      # Subscriptions
      - |
        LEEK_AGENT_SUBSCRIPTIONS=
        [
          {
            "broker": "redis://xxx/0",
            "backend": null,
            "exchange": "celeryev",
            "queue": "leek.fanout",
            "routing_key": "#",
            "org_name": "womo",
            "app_name": "womo",
            "app_env": "prod",
            "prefetch_count": 200,
            "api_url":  "https://leek-api.womo.site",
            "app_key": "not-secret",
            "concurrency_pool_size": 20
          }
        ]
      - LEEK_AGENT_API_SECRET=not-secret
    ports:
      - 5001:5000
      - 8000:8000
```
This is agent docker

**Comment by yswtrue** [comment] 2021-11-06 10:02
and agent will restart sometime.
The log is here #45

**Comment by yswtrue** [comment] 2021-11-06 10:04
```
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = False
CELERY_WORKER_HIJACK_ROOT_LOGGER = True
```
celery config is here.

**Comment by AdamiHamza** [comment] 2021-11-17 20:42
This is not Leek limitation, bellow is an example of Leek on a 7 days window, processed over 40 millions event without crashing the broker.

I assume your celery cluster is running on low resources and couldn't handle the load from workers events.

<img width="1713" alt="Screen Shot 2021-11-17 at 21 35 14" src="https://user-images.githubusercontent.com/26749638/142278498-e00ba06b-09d1-4855-b585-a58bf7d206da.png">

**Comment by yswtrue** [comment] 2021-11-20 16:57
> This is not Leek limitation, bellow is an example of Leek on a 7 days window, processed over 40 millions event without crashing the broker.
> 
> I assume your broker cluster is running on low resources and couldn't handle the load from workers events.
> 
> <img alt="Screen Shot 2021-11-17 at 21 35 14" width="1713" src="https://user-images.githubusercontent.com/26749638/142278498-e00ba06b-09d1-4855-b585-a58bf7d206da.png">

Sometimes we have almost 1 million tasks in one hour, should I increase concurrency_pool_size or prefetch_count

**Comment by yswtrue** [comment] 2021-11-20 16:58
I have tested Prometheus metrics, but it leaks some information, I think this project is the best way to monitor celery.

**Comment by AdamiHamza** [comment] 2021-11-24 14:34
@yswtrue sometimes we also have bursts of millions of events in hours, so let me explain how we solved that with competing consumers:

So we have:

- One app and 3 subscriptions 
  - `core-qa`: prefetch count 1000 and pool size 3
  - `core-demo`: prefetch count 1000 and pool size 3
  - `core-prod`: prefetch count 1000 and pool size 20

- Leek main service: with just one ECS task that has Leek agent, api and web enabled and it's always up

- Leek workers service: it has only the agent and the api enabled, no web app, no load balancer. the workers service can have multiple tasks depending on `leek.fanout` queue depth, we have an auto scaling policy that increases workers count on every increase on queue depth and vise-versa. the initial desired count is set to 0 so when there is no load there will be no workers to process the events quickly, but during rush hours Leek workers will scale automatically to handle the burst.

```
module "autoscaling_worker_leek" {
  source      = "../../../../modules/aws/autoscaling/ecs-amq"
  prefix      = local.prefix
  common_tags = local.common_tags

  enable      = true
  broker_name = "prd-sum-useast1-core-amq"
  queue_name  = "leek.fanout"

  cluster_name = module.common.ecs_cluster["name"]
  service = {
    name         = module.leek.services_names["worker"]
    min_capacity = 0
    max_capacity = 2
  }

  step_adjustments = {
    "step1" = {
      lower_bound        = 0
      upper_bound        = 10000
      scaling_adjustment = 0
    }
    "step2" = {
      lower_bound        = 10000
      upper_bound        = 100000
      scaling_adjustment = 1
    }
    "step3" = {
      lower_bound        = 100000
      upper_bound        = null
      scaling_adjustment = 2
    }
  }
}
```

`concurrency_pool_size` is just for asynchronous IO requests to Leek API. to be able to process events much faster with a cost effective approach I advise you to setup autoscaling for Leek.

In addition to this, please monitor your ElasticSearch cluster, sometimes ElasticSearch may be the reason why Leek can't process tasks much faster because ElasticSearch can't index the events much faster. for example we've seen major improvements after switching from a General Purpose AWS Elasticsearch node to a Memory Optimized Elasticsearch node. now we are using `r6g.large.elasticsearch` as instance type and its performance is great.

I also recommend you to move to a managed ElasticSearch service Like AWS Opensearch, a miss configuration in Elasticsearch can also lead to slow events processing.

**Comment by yswtrue** [comment] 2021-11-25 09:45
thank you very much, I will try it later.

**Comment by nicon89** [comment] 2022-03-09 12:06
I have same issue.
Freeable memory on Redis since starting leek:
![obraz](https://user-images.githubusercontent.com/9640905/157438703-acd1c82a-3aba-4a28-971e-0ccce205370c.png)

**Comment by nicon89** [comment] 2022-03-16 14:46
5.1.2

**Comment by kodless** [comment] 2022-03-23 01:43
Closing this because I couldn't reproduce the issue, and I think this is an upstream celery issue that was fixed a long time ago as stated in the comment above.

**Closed by kodless** 2022-03-23 01:43 UTC
